import { defineConfig } from 'tsup'
import path from 'path'
import fg from 'fast-glob'
import fs from 'fs'

const files = fg.sync(['src/**/*.ts']).filter((f) => !/(spec|.d.ts)/.test(f))

const indexPath = path.resolve(__dirname, 'src/index.ts')

let indexContent = `// auto generated by build script`

files.forEach((f) => {
    const name = path.basename(f, '.ts')
    
    if (name === 'index') return

    indexContent += `\nexport * from './${name}'`
})

fs.writeFileSync(indexPath, indexContent)

if (!files.includes('src/index.ts')) {
    files.push('src/index.ts')
}

export default defineConfig({
    entry: files,
    splitting: false,
    sourcemap: true,
    clean: true,
    dts: true,
    format: ['esm', 'cjs'],
    tsconfig: path.resolve(__dirname, 'tsconfig.json'),
})