name: Deploy site

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      
      - uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: ~/.npm
          key: ${{ hashFiles('packages/docs/package-lock.json') }}

      - name: install_dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm -w docs install

      - name: build
        run: npm -w docs run generate
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/.output/public
          commit_message: ${{ github.event.head_commit.message }}